### ISSUE TITLE
scientific cannot be used with alternative Integer implementations

### ISSUE THREAD

**Issue by ygale** [basvandijk/scientific#15]
GHC allows using an implementation for `Integer` that is different than the default implementation based on GNU GMP. scientific is becoming a common dependency - because it's a great library, thanks! - but at the same time, it is also becoming increasingly common to use alternative `Integer` implementations. So scientific should have a cabal flag that allows bypassing the efficient implementation in `Math.NumberTheory.Logarithm` which depends on GMP internals, and using instead a more naive implementation that only uses the generic `Integer` API.

**Comment by quyse** [comment]
Hi, `scientific` now have `integer-logarithms` as a dependency, which in turn depends on `integer-gmp` unconditionally, so now again `scientific` cannot be used with `integer-simple`. May it be fixed somehow?

**Comment by basvandijk** [comment]
Hi @quyse, thanks for the heads-up. @phadej could you make `integer-logarithms` work with `integer-simple`. I'll open a issue for it.

BTW as explained in [this thread](https://mail.haskell.org/pipermail/libraries/2017-January/027588.html) on the Haskell libraries mailinglist, I'm thinking of publishing an [integer](https://github.com/basvandijk/integer) package which reexports the common parts of `integer-simple` and `integer-gmp`. This should make it easier to define packages like `integer-logarithms` and `scientific` because those then don't need to add cabal flags.

**Comment by phadej** [comment]
I can. On it.

**Comment by phadej** [comment]
@quyse can you test whether your setup works with https://github.com/Bodigrim/integer-logarithms/pull/2 ?

**Comment by phadej** [comment]
@basvandijk for the record: http://hackage.haskell.org/package/integer-logarithms-1/docs/GHC-Integer-Logarithms-Compat.html seems to be one of the module you want from `integer`. OTOH it has to do shim on `GHC-7.0`, cannot be just re-export.

**Comment by quyse** [comment]
@phadej Seems working! I checked with stack that `scientific-0.3.4.10` and `integer-logarithms` from your PR are built successfully with `--ghc-variant integer-simple --flag scientific:integer-simple --flag integer-logarithms:-integer-gmp`. Thank you!

**Comment by phadej** [comment]
@quyse http://hackage.haskell.org/package/integer-logarithms-1.0.1 here you go

**Comment by basvandijk** [comment]
Thanks @phadej and @quyse!
