### ISSUE TITLE
Division bug?

### ISSUE THREAD

**Issue by jefdaj** [basvandijk/scientific#56]
This hangs with 100% CPU on my machine:

```haskell
(read "1.0" :: Scientific) / (read "6.0" :: Scientific)
```

Have I stumbled on a bug in division, or parsing, or am I doing something wrong? It only happens with certain numbers. For example "4.0" instead of "6.0" works.

**Comment by jefdaj** [comment]
Never mind, this is what `fromRationalRepetend` is for right?

**Comment by basvandijk** [comment]
1/6 is a [repeating decimal](https://en.wikipedia.org/wiki/Repeating_decimal): 0.1(6). Since a `Scientific` stores the actual decimal digits representing an infinite number of them takes infinite time and space.

Indeed use [fromRationalRepetend](http://hackage.haskell.org/package/scientific-0.3.5.2/docs/Data-Scientific.html#v:fromRationalRepetend). Do note that this function consumes space linear in the number of digits in the resulting scientific. For 0.1(6) that's not a problem though since the repetition starts very early.

Can you tell a bit more about your use-case?
